// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDITdSqIwDRtgzHwRWH1e3TNUfnWNDrUgM',
    appId: '1:311581491549:web:5b4df1d65c0e565835e8b4',
    messagingSenderId: '311581491549',
    projectId: 'my-first-project-cc7ea',
    authDomain: 'my-first-project-cc7ea.firebaseapp.com',
    storageBucket: 'my-first-project-cc7ea.firebasestorage.app',
    measurementId: 'G-GJLQ5EHP1M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3W9dLM3M40MEe58vjYTJJPwljQRfDcgU',
    appId: '1:311581491549:android:ddf7853de9bb243035e8b4',
    messagingSenderId: '311581491549',
    projectId: 'my-first-project-cc7ea',
    storageBucket: 'my-first-project-cc7ea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIAynHBGOIukByCUYe2S927rNNOw2CzNA',
    appId: '1:311581491549:ios:79364b0b6871592b35e8b4',
    messagingSenderId: '311581491549',
    projectId: 'my-first-project-cc7ea',
    storageBucket: 'my-first-project-cc7ea.firebasestorage.app',
    iosBundleId: 'com.example.firebaseProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIAynHBGOIukByCUYe2S927rNNOw2CzNA',
    appId: '1:311581491549:ios:79364b0b6871592b35e8b4',
    messagingSenderId: '311581491549',
    projectId: 'my-first-project-cc7ea',
    storageBucket: 'my-first-project-cc7ea.firebasestorage.app',
    iosBundleId: 'com.example.firebaseProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDITdSqIwDRtgzHwRWH1e3TNUfnWNDrUgM',
    appId: '1:311581491549:web:50cfe35efaa1169135e8b4',
    messagingSenderId: '311581491549',
    projectId: 'my-first-project-cc7ea',
    authDomain: 'my-first-project-cc7ea.firebaseapp.com',
    storageBucket: 'my-first-project-cc7ea.firebasestorage.app',
    measurementId: 'G-ZBZCRGJD91',
  );
}
